const usersData = [
  {
    id: 1,
    name: "John",
    lastName: "Doe",
    title: "Software Developer",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
    score: 0,
    email: "enes.a@enuygun.com",
    phone: "0555 555 55 55",
  },
  {
    id: 2,
    name: "Jane",
    lastName: "Doe",
    title: "Project Manager",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
    score: 0,
    email: "deniz.s@enuygun.com",
    phone: "0555 555 55 55",
  },
  {
    id: 3,
    name: "Bob",
    lastName: "Smith",
    title: "Designer",
    image: "https://randomuser.me/api/portraits/men/2.jpg",
    score: 0,
    email: "ayla.a@enuygun.com",
    phone: "0555 555 55 55",
  },
  {
    id: 4,
    name: "James",
    lastName: "Smith",
    title: "Engineer",
    image: "https://randomuser.me/api/portraits/men/3.jpg",
    score: 0,
    email: "james.smith@example.com",
    phone: "+1 (555) 123-4567",
  },
  {
    id: 5,
    name: "Emma",
    lastName: "Johnson",
    title: "Designer",
    image: "https://randomuser.me/api/portraits/women/5.jpg",
    score: 0,
    email: "emma.johnson@example.com",
    phone: "+1 (555) 234-5678",
  },
  {
    id: 6,
    name: "Noah",
    lastName: "Williams",
    title: "Developer",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
    score: 0,
    email: "noah.williams@example.com",
    phone: "+1 (555) 345-6789",
  },
  {
    id: 7,
    name: "Olivia",
    lastName: "Brown",
    title: "Manager",
    image: "https://randomuser.me/api/portraits/men/4.jpg",
    score: 0,
    email: "olivia.brown@example.com",
    phone: "+1 (555) 456-7890",
  },
  {
    id: 8,
    name: "Ethan",
    lastName: "Davis",
    title: "Manager",
    image: "https://randomuser.me/api/portraits/men/6.jpg",
    score: 0,
    email: "ethan.davis@example.com",
    phone: "+1 (555) 123-4567",
  },
  {
    id: 9,
    name: "Sophia",
    lastName: "Garcia",
    title: "Engineer",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
    score: 0,
    email: "sophia.garcia@example.com",
    phone: "+1 (555) 234-5678",
  },
  {
    id: 10,
    name: "Liam",
    lastName: "Hernandez",
    title: "Developer",
    image: "https://randomuser.me/api/portraits/women/7.jpg",
    score: 0,
    email: "liam.hernandez@example.com",
    phone: "+1 (555) 345-6789",
  },
  {
    id: 11,
    name: "Isabella",
    lastName: "Lopez",
    title: "Designer",
    image: "https://randomuser.me/api/portraits/women/8.jpg",
    score: 0,
    email: "isabella.lopez@example.com",
    phone: "+1 (555) 456-7890",
  },
  {
    id: 12,
    name: "Evelyn",
    lastName: "Brown",
    title: "Manager",
    image: "https://randomuser.me/api/portraits/women/9.jpg",
    score: 0,
    email: "evelyn.brown@example.com",
    phone: "+1 (555) 123-4567",
  },
  {
    id: 13,
    name: "Daniel",
    lastName: "Smith",
    title: "Engineer",
    image: "https://randomuser.me/api/portraits/men/9.jpg",
    score: 0,
    email: "daniel.smith@example.com",
    phone: "+1 (555) 234-5678",
  },
  {
    id: 14,
    name: "Victoria",
    lastName: "Garcia",
    title: "Developer",
    image: "https://randomuser.me/api/portraits/women/10.jpg",
    score: 0,
    email: "victoria.garcia@example.com",
    phone: "+1 (555) 345-6789",
  },
  {
    id: 15,
    name: "Samuel",
    lastName: "Taylor",
    title: "Designer",
    image: "https://randomuser.me/api/portraits/men/11.jpg",
    score: 0,
    email: "samuel.taylor@example.com",
    phone: "+1 (555) 456-7890",
  },
  {
    id: 16,
    name: "Sophie",
    lastName: "Davis",
    title: "Manager",
    image: "https://randomuser.me/api/portraits/women/11.jpg",
    score: 0,
    email: "sophie.davis@example.com",
    phone: "+1 (555) 567-8901",
  },
  {
    id: 17,
    name: "Gabriel",
    lastName: "Rodriguez",
    title: "Engineer",
    image: "https://randomuser.me/api/portraits/men/12.jpg",
    score: 0,
    email: "gabriel.rodriguez@example.com",
    phone: "+1 (555) 678-9012",
  },
  {
    id: 18,
    name: "Madison",
    lastName: "Miller",
    title: "Developer",
    image: "https://randomuser.me/api/portraits/men/13.jpg",
    score: 0,
    email: "madison.miller@example.com",
    phone: "+1 (555) 789-0123",
  },
];

const resolvers = {
  Query: {
    users: () => usersData,
    user(parent, args, contextValue, info) {
      return usersData.filter((user) => user.id == args.id)[0];
    },
  },
};

module.exports = resolvers;
